// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var $$Array = require("bs-platform/lib/js/array.js");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var ReactHelmet = require("react-helmet");
var Js_null_undefined = require("bs-platform/lib/js/js_null_undefined.js");

function make(htmlAttributes, titleTemplate, meta, title, children) {
  var meta$1 = meta !== undefined ? $$Array.of_list(meta) : /* array */[];
  return ReasonReact.wrapJsForReason(ReactHelmet.default, {
              htmlAttributes: Js_null_undefined.fromOption(htmlAttributes),
              title: title,
              titleTemplate: Js_null_undefined.fromOption(titleTemplate),
              meta: meta$1
            }, children);
}

var Helmet = /* module */[/* make */make];

exports.Helmet = Helmet;
/* ReasonReact Not a pure module */
